### ISSUE TITLE
bestanden moeten ook op GitHub

### ISSUE THREAD

**Issue by Theo-denBlanken** [sohilalami/albumcovers#1]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/sohilalami/albumcovers/blob/master/

Feedback: Daar is dat voor bedoeld[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"reviewer":"Theo-denBlanken"}')

**Comment by sohilalami** [comment]
Alle bestand zijn nu geïmporteerd

**Comment by Theo-denBlanken** [comment]
Dag Sohil, 
ik zie dat je een nieuwe repo aangemaakt het. Daar staan de bestanden nu wel. Die hadden al het goed is ook in deze repo gekund hoor. het is immers een versie-beheersysteem. Het is nu niet nodig dit als nog te doen.
